baseurl = "https://ds-incubator.netlify.com/"
title = "Back to posts"
theme = "ghostwriter"
author = "Mauro Lepore, CJ Yetman, Klaus Hagedorn, and Clare Murray"
languageCode = "en-us"
copyright = "2dii"
disqusShortname = "ds-incubator"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]

[Author]
    name = "2° Investing Initiative"
    profile = "https://github.com/orgs/2DegreesInvesting/people"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "ds-incubator"
    description = "Share best practices in coding"
    github = "https://github.com/2DegreesInvesting/ds-incubator"
    twitter = "https://twitter.com/2degreesinvest"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"
